### ISSUE TITLE
Throwing in handler terminates node process

### ISSUE THREAD

**Issue by pke** [lukeed/polka#115] opened 2019-11-08 10:25 UTC
Coming from koa I wonder how to protect polka from crashing the node process in case of an uncaught exception/promise rejection in one of the middlewares/handlers?
Shouldn't that just result in a 500 error but not an exit of the node process?

**Comment by lukeed** [comment] 2019-11-08 17:56
This is a duplicate of #12. The TLDR is that:

A) this is fixed in the `@next` release and will be doable in 1.0
B) this is my recommendation for current `0.x`/stable release: https://github.com/lukeed/polka/issues/12#issuecomment-486089751

Hope that helps!

**Closed by lukeed** 2019-11-08 17:56 UTC
Labels: duplicate
