### ISSUE TITLE
res.json() | json is not a function

### ISSUE THREAD

**Issue by darklight147** [lukeed/polka#155] opened 2021-01-16 17:19 UTC

**Comment by TrySound** [comment] 2021-01-16 17:40
This is express specific api which polka does not cover. Please list your middlewares so we could address the issue to the right project.

**Comment by darklight147** [comment] 2021-01-16 19:00
i only tried to user res object from polka, i didnt import express

`import polka from 'polka';

const app = polka().listen(5050);

app.get('/test', (req, res) => {
	console.log('Called');
	res.json({
		status: 200,
	});
});
`

**Comment by lukeed** [comment] 2021-01-16 19:13
As @TrySound mentioned, there is no `res.json` by default. It doesn't exist on native the `http` object. Polka only serves as a router and as a middleware executor. Everything else (that isn't native) has to be brought/defined.

In the next major version of Polka, there will be an Express-compat version that has (nearly) all built-ins ready to go for the Express user.

But for now, you can do something like this:

```js
polka()
  .use((req, res, next) => {
    res.json = d => {
      res.setHeader('content-type', 'application/json');
      res.end(JSON.stringify(d));
    };
    next();
```

Closing as a duplicate of #5 
Hope that helps!

**Closed by lukeed** 2021-01-16 19:13 UTC
