### ISSUE TITLE
req.query does not handle query parts containing equals sign (=)

### ISSUE THREAD

**Issue by claudijo** [lukeed/polka#123] opened 2020-01-09 13:24 UTC
If url is `www.example.com?q=a?b=c`

req.query is `{ 'q': 'a?b' }`

but expected req.query is `{ 'q': 'a?b=c' }`

**Comment by lukeed** [comment] 2020-01-12 02:20
This is correct. It's not the `=` that causes problems – it's the extra `?` in your query string.

What you have here is an invalid URL that violates the URL spec (https://url.spec.whatwg.org/#url-query-string). You can see this happen anywhere that URLs get parsed, for example:

```js
// Node
const querystring = require('querystring');

querystring.parse('?q=a?b=c'.substring(1));
//=> { q: 'a?b=c' }

// Node AND Browser
new URL('https://example.com/foo?q=a?b=c').searchParams;
// => { 'q' => 'a?b=c' }
```

If you're saying that `q` is equal to that string then you have to wrap those values within `encodeURIComponnt` so that they can be parsed correctly.

If you're simply saying that `q=a` and `b=c` then you need to the `&` joiner for multiple key=value segments: `www.example.com?q=a&b=c`. You're only allowed one `?` as it marks the start of a query string.

Hope that helps!

**Comment by claudijo** [comment] 2020-01-13 09:52
Thanks for looking in to this. I don't wish to take up more of your time, but I'm not quite sure I get your point... 

The examples you state indicate that the produced query property of the req objects should be the same as I mention as "expected" in the initial message, which is `{ 'q': 'a?b=c' }` and not the actual outcome I see when using polka in my node app, which is `{ 'q': 'a?b' }`.

Also from what I can see in the RFC3986 spec (https://tools.ietf.org/html/rfc3986#section-3.4), "...question mark ("?") may represent data within the query component.", so  it's the extra `?` shouldn't cause a problem.

**Comment by lukeed** [comment] 2020-01-13 13:39
Hmm.. I'm not sure I get my point either :sweat_smile: sorry, wasn't feeling great this weekend.

Going to take another look

**Comment by claudijo** [comment] 2020-01-13 14:19
I tried to make a minimal code example that has this problem and noticed that it is not present in the current polka version(!) I had to install polka@1.0.0-next.6 to get the problem...

Simple code example to reproduce the problem
```
const polka = require('polka');

polka()
  .get('/', (req, res) => {
    res.end(`Root req query: ${JSON.stringify(req.query)}`);
  })
  .listen(3000, err => {
    if (err) throw err;
    console.log(`> Running on localhost:3000`);
  });
```

**Comment by lukeed** [comment] 2020-01-13 14:24
Yup, it's the `@next` only :) The current master doesn't even convert the string into an object – instead that happens inside polka directly [using the native `querystring` module](https://github.com/lukeed/polka/blob/master/packages/polka/index.js#L89).

I'm fixing it right now for next.

**Comment by lukeed** [comment] 2020-01-13 14:49
Cool, fixed now. Also made it a bit faster too 😼 

```
# DECODE: "/f%C3%B8%C3%B8%C3%9F%E2%88%82r?phone=%2b393383123549"
(before)
  @polka/url     x 671,500 ops/sec ±0.30% (193 runs sampled)
(after)
  @polka/url     x 792,495 ops/sec ±0.36% (194 runs sampled)
```

Releasing a new version now.

Thanks for the report & for your patience 😄

**Closed by lukeed** 2020-01-13 14:49 UTC

**Comment by claudijo** [comment] 2020-01-13 14:57
Cool.

I just cloned the repo and could not reproduce the problem in the `next` branch :-/

Updated the test according to the following, and they passed... Guess you fixed it before I cloned(?)

```diff
diff --git a/tests/polka.js b/tests/polka.js
index 29bb29b..f3603d7 100644
--- a/tests/polka.js
+++ b/tests/polka.js
@@ -443,9 +443,9 @@ test('polka::usage::sub-apps', async t => {
        }).get('/:bar', (req, res) => {
                t.pass('runs the sub-application /:id route');
                t.is(req.params.bar, 'hi', '~> parses the sub-application params');
-               t.is(req.url, '/hi?a=0', '~> trims basepath from `req.url` value');
-               t.same(req.query, {a:'0'}, '~> parses the sub-application `res.query` value');
-               t.is(req.originalUrl, '/sub/hi?a=0', '~> preserves original `req.url` value');
+               t.is(req.url, '/hi?q=a?b=c', '~> trims basepath from `req.url` value');
+               t.same(req.query, {q:'a?b=c'}, '~> parses the sub-application `res.query` value');
+               t.is(req.originalUrl, '/sub/hi?q=a?b=c', '~> preserves original `req.url` value');
                t.is(req.foo, 'hello', '~> receives mutatations from main-app middleware');
                t.is(req.bar, 'world', '~> receives mutatations from own middleware');
                res.end('hello from sub@show');
@@ -475,7 +475,7 @@ test('polka::usage::sub-apps', async t => {
        t.is(r2.data, 'hello from main', '~> received "hello from main" response');
 
        // check sub-app pattern route
-       let r3 = await axios.get(`${uri}/sub/hi?a=0`)
+       let r3 = await axios.get(`${uri}/sub/hi?q=a?b=c`)
        t.is(r3.status, 200, '~> received 200 status');
        t.is(r3.data, 'hello from sub@show', '~> received "hello from sub@show" response');
```

Anyhow, all seems good :)

**Comment by lukeed** [comment] 2020-01-13 15:02
Sorry, could not reproduce what problem?

Tests should be fine since that forces a `lerna bootstrap` step in pretest, which enforces that all dependency links are up to date.

**Comment by claudijo** [comment] 2020-01-13 15:14
Reproduce the original parse problem for query strings.. 

Sorry to add to the confusion, but I realized I updated the tests according to the diff above on the master branch, not the next branch. So never mind :)

Thanks for the fix and perf improvement :)

**Comment by lukeed** [comment] 2020-01-13 15:29
Ah gotcha, no worries!
