### ISSUE TITLE
`next` is undefined when using sub-apps for routing

### ISSUE THREAD

**Issue by claudijo** [lukeed/polka#109] opened 2019-09-24 20:09 UTC
This code will have the next argument defined:

```js
const app = polka();

app.post('/api', (req, res, next) => {
  console.log('next is', next); // next is err => err ? this.onError(err, req, res, next) : loop()
});
```

However, isn't the following code where a sub app is used for routing also supposed to have the next argument defined?

```js
const app = polka();
const subApp = polka();

subApp.post('/', (req, res, next) => {
  console.log('next is', next); // next is undefined
});

app.use('/api', subApp);
```

... or am I missing something here?

**Comment by lukeed** [comment] 2019-09-24 21:34
Hey, Yes this is true of the current stable release.
It's been fixed in `@next` (which you can start using now) and will remain fixed going forward.

This is technically a duplicate of #77 and so I will be closing this.
Thanks for reporting though :)

**Closed by lukeed** 2019-09-24 21:34 UTC
Labels: duplicate, has fix
