### ISSUE TITLE
Error: Cannot find module 'node:querystring'

### ISSUE THREAD

**Issue by sayumani** [lukeed/polka#216] opened 2024-09-18 09:00 UTC
Getting this error while building our ui repositories 

Error: Cannot find module 'node:querystring'
![Screenshot 2024-09-18 at 10 04 22 AM](https://github.com/user-attachments/assets/21518a96-7b99-43c1-9cee-9c7cb71d906d)

**Comment by lukeed** [comment] 2024-09-19 13:45
Thanks, closing as duplicate of #215

**Closed as not planned by lukeed** 2024-09-19 13:45 UTC
